<?php

namespace MTConnectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ColetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColetaRepository extends EntityRepository
{
}
