<?php

namespace MTConnectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DataSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataSetRepository extends EntityRepository
{
    public function findLastSequenceFlushed(){
        $em = $this->getEntityManager();
        $highest_seq = $em->createQueryBuilder()
            ->select('MAX(ds.sequence)')
            ->from('MTConnectBundle:DataSet', 'ds')
            ->getQuery()
            ->getSingleScalarResult();
        return $highest_seq;
    }

    public function findPreview($coleta,$limit){
        $em = $this->getEntityManager();
        $highest_seq = $em->createQueryBuilder()
            ->select('ds')
            ->from('MTConnectBundle:DataSet', 'ds')
            ->where('ds.coleta ='.$coleta)
            ->orderBy('ds.timestamp','DESC')
            ->setMaxResults( $limit )
            ->getQuery()
            ->getResult();
        return $highest_seq;
    }

    public function findByColetaArray($coleta){
        $em = $this->getEntityManager();
        $result = $em->createQueryBuilder()
            ->select('ds')
            ->from('MTConnectBundle:DataSet', 'ds')
            ->where('ds.coleta ='.$coleta)
            ->orderBy('ds.timestamp','DESC')
            ->getQuery()
            ->getArrayResult();
        return $result;
    }
}
