<?php

namespace MTConnectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DataSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataSetRepository extends EntityRepository
{
}
