<?php

namespace MTConnectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DataItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataItemRepository extends EntityRepository
{
}
